title: My Jekyll Blog
description: Blog SEO dengan Jekyll
baseurl: "https://bloghugo.github.io/jekyllgpt/"
url: "https://bloghugo.github.io/jekyllgpt/"
theme: minima
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
